feat: get public service by id
Informasjonsforvaltning/service-catalog pull request #21
Opened 2023-10-30 12:44 UTC by pooriamehregan

resolves https://github.com/Informasjonsforvaltning/service-catalog/issues/9

2023-10-30 13:05 UTC, NilsOveTen requested changes

2023-10-30 13:05 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/service_catalog/mongodb/PublicServiceRepository.kt
> +    fun getByCatalogIdAndId(catalogId: String, id: String): PublicService?
```suggestion
```

2023-10-30 13:05 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/service_catalog/mongodb/PublicServiceRepository.kt
> +    fun getByCatalogIdAndId(catalogId: String, id: String): PublicService?
Bruk heller den innebygde `getByIdOrNull` og så sjekk at den har korrekt catalogId etterpå

2023-10-31 07:53 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/service_catalog/service/PublicServiceService.kt
> +        }
```suggestion
        publicServiceRepository.findByIdOrNull(id)
        ?.takeIf { it.catalogId === catalogId }
```

2023-10-31 08:18 UTC, pooriamehregan commented on src/main/kotlin/no/digdir/service_catalog/service/PublicServiceService.kt
> +        }
Ja, fikset den nå.

2023-10-31 08:27 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/service_catalog/service/PublicServiceService.kt
> +        }
og flytt takeIf ned på en ny linje, det blir vanskeligere å lese koden når du kjører to metoder på samme linje
```suggestion
        publicServiceRepository.findByIdOrNull(id)
            ?.takeIf { it.catalogId == catalogId }
```

2023-10-31 08:29 UTC, NilsOveTen commented on src/main/kotlin/no/digdir/service_catalog/service/PublicServiceService.kt
> +        }
Hvis du føler at du må ha innholdet i takeIf på en egen linje så kan du gjøre det etterpå
```suggestion
        publicServiceRepository.findByIdOrNull(id)
            ?.takeIf {
                it.catalogId == catalogId
            }
```

2023-10-31 14:16 UTC, NilsOveTen approved these changes

2023-11-01 07:41 UTC, merged